# Generated by Django 3.2.9 on 2022-03-17 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0003_auto_20220317_0756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-comment_date',)},
        ),
    ]
